# This contains params to be used by the stages to train or predict
prepare :
  split : 0.3
  seed : 2022
  tags : <python>

featurize :
  max_features : 2500
  n_grams : 2

train :
  seed : 2023
  n_est : 100
  min_split : 16
  n_jobs : 2